refactor(StudentDataService): Move visitedNodesHistory to NodeStatusService
WISE-Community/WISE-Client pull request #1170
Opened 2023-04-07 17:02 UTC by hirokiterashima

## Changes
- Move StudentDataService.visitedNodesHistory to NodeStatusService.nodeIdToIsVisited and make it into a map of [nodeId, isVisited] values, which is populated/updated when
   - The student data is retrieved (for student and preview)
   - Student visits a node

## Test
- IsVisited values in NodeStatuses are calculated and saved as before. Check the StudentStatus that is saved each time you visit a step and verify that on the steps that you've visited has isVisited set to true.

Closes #1169

2023-04-09 17:30 UTC, geoffreykwan requested changes
When the student loads a run for the first time, the first step that is loaded has isVisited set to false in the student status even though it should be true. This problem exists on the develop branch so if it's not a simple fix we can fix it in another issue.

2023-04-09 17:30 UTC, geoffreykwan commented on src/assets/wise5/services/nodeStatusService.ts
> +  }
This can be done in a single loop.

2023-04-10 17:00 UTC, hirokiterashima commented
Let's address the issue in a separate task. This PR should focus on refactoring.

2023-04-10 21:41 UTC, geoffreykwan approved these changes
Looks good.

2023-04-10 23:42 UTC, merged