feat(Run): Allow teachers to archive runs
WISE-Community/WISE-Client pull request #1173
Opened 2023-04-09 16:44 UTC by geoffreykwan

## Changes

- Teachers can now archive runs
- There is now an active runs view and an archived runs view

## Test

- Archive/unarchive a run using the run menu list
- Archive/unarchive a run using the checkbox and then the "Archive Selected" button
- Make sure the select all runs checkbox works properly
- Make sure the select runs drop down works properly for (all, none, running, completed)
- Make sure switching from the active to archived view works properly

Closes #1012

2023-08-22 16:48 UTC, hirokiterashima reviewed
I added some comments. Also, should we use "Archive/Unarchive Unit" instead of "Archive/Unarchive Run"? We want teachers to think in "unit", not "run"?

2023-08-22 16:48 UTC, hirokiterashima commented on src/app/teacher/teacher-run-list/teacher-run-list.component.html
> +  </div>
TeacherRunListComponent is getting big. Can we make this block into a new component?

2023-08-22 16:48 UTC, hirokiterashima commented on src/app/teacher/run-menu/run-menu.component.ts
> +  }
Duplication. Can you try refactoring it?

2023-08-22 16:48 UTC, hirokiterashima commented on src/app/services/archive-project.service.ts
> +  }
Instead of ```Observable<any>```, is it ```Observable<ArchiveProjectResponse[]>```?

2023-08-25 07:06 UTC, breity requested changes
Looking great. I updated styles and layout, as well as some text, accessibility elements, etc.
@geoffreykwan There are two failing tests that I'm having trouble fixing. Maybe we could take a look.

I have 1 suggestion: We should add a confirmation dialog when user chooses to archive or restore multiple runs at once. @hirokiterashima and @geoffreykwan, what do you think?

These are the issues I found that we discussed:
1. Selecting all the runs using the top checkbox doesn't select shared runs.
2. All the user's runs are shown now when loading the run list. We used to only show the latest 10 and let users view the rest with the 'Show All' button.

2023-08-25 15:59 UTC, hirokiterashima commented
New style changes look good. 

I wonder if asking users to confirm each time is a bit disruptive, especially since it's easy to undo their changes in the archive/unarchive views if they make a mistake by accident. How about adding an 'undo' button in the toast message, like in Gmail?

2023-08-28 18:23 UTC, hirokiterashima commented
The new undo feature works great.

Should we hide or disable the SelectRunsControls if there are no runs to select? It seems a bit strange to have it there.
<img width="1231" alt="Screenshot 2023-08-28 at 11 20 42 AM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/d1ab88f9-c66b-4e57-82c0-c4645e3431d3">

2023-08-28 18:33 UTC, breity commented
> Should we hide or disable the SelectRunsControls if there are no runs to select? It seems a bit strange to have it there. 
Ah yes. We should.

2023-08-29 17:39 UTC, hirokiterashima requested changes
It's getting there. As discussed this morning, here are some more changes to make:

1. In both active and archive views, add “scheduled” select-option, and show the option order as follows: All -> None -> Completed -> Running -> Scheduled

2. Change message when there are no active runs to “Hey there! Looks like you don't have any active classroom units.\n\nBrowse the "Unit Library" to find titles to use with your students.” Also remove the count message.

3. Change message when there are no archived runs to “You don’t have any archived classroom units.” Also remove the count message.

4. See minor code comments inline

2023-08-29 17:39 UTC, hirokiterashima commented on src/app/teacher/run-menu/run-menu.component.ts
> +  @Output() runArchiveStatusChangedEvent: EventEmitter<any> = new EventEmitter<any>();
Looks like we don't do anything with the emitted value, so make it void?
```suggestion
  @Output() runArchiveStatusChangedEvent: EventEmitter<void> = new EventEmitter<void>();
```

2023-08-29 17:39 UTC, hirokiterashima commented on src/app/teacher/run-menu/run-menu.component.ts
> +    this.runArchiveStatusChangedEvent.emit(run);
Looks like we don't do anything with the emitted value, so make it void?
```suggestion
    this.runArchiveStatusChangedEvent.emit();
```

2023-08-29 17:39 UTC, hirokiterashima commented on src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.ts
> +  @Output() runSelectedStatusChangedEvent: EventEmitter<any> = new EventEmitter<any>();
Looks like we don't do anything with the emitted value, so make it void?
```suggestion
  @Output() runArchiveStatusChangedEvent: EventEmitter<void> = new EventEmitter<void>();
  @Output() runSelectedStatusChangedEvent: EventEmitter<void> = new EventEmitter<void>();
```

2023-08-31 18:16 UTC, hirokiterashima requested changes
I added some code suggestions to prevent adding new code duplication issues in the TeacherRunListComponent spec file. I referenced [Jasmine style guide](https://github.com/CareMessagePlatform/jasmine-styleguide).

I also think using a new SelectRunsOption enum to represent available options will make the code clearer, so I added some suggestions inline for that as well. Lmk what you think or have any questions.

2023-08-31 18:16 UTC, hirokiterashima commented on src/app/teacher/teacher-run-list/teacher-run-list.component.spec.ts
> +}
This block introduces duplication. How about writing it this way? Also, let's read and discuss [Jasmine style guide](https://github.com/CareMessagePlatform/jasmine-styleguide) to standardize how we structure/write unit tests.
```suggestion
function selectRunsOptionChosen(): void {
  describe('selectRunsOptionChosen()', () => {
    beforeEach(() => {
      setRun2Completed();
    });
    selectAllOptionChosen();
    selectNoneOptionChosen();
    selectCompletedOptionChosen();
    selectRunningOptionChosen();
    selectScheduledOptionChosen();
  });
}

function selectAllOptionChosen(): void {
  it('should select all runs', async () => {
    await clickSelectRunsMenuButtonAndExpectSelected('All', [true, true, true]);
  });
}

function selectNoneOptionChosen(): void {
  it('should select no runs', async () => {
    await clickSelectRunsMenuButtonAndExpectSelected('None', [false, false, false]);
  });
}

function selectCompletedOptionChosen(): void {
  it('should select completed runs', async () => {
    await clickSelectRunsMenuButtonAndExpectSelected('Completed', [false, true, false]);
  });
}

function selectRunningOptionChosen(): void {
  it('should select running runs', async () => {
    await clickSelectRunsMenuButtonAndExpectSelected('Running', [true, false, true]);
  });
}

function selectScheduledOptionChosen(): void {
  it('it should select scheduled runs', async () => {
    setRun3Scheduled();
    await clickSelectRunsMenuButtonAndExpectSelected('Scheduled', [true, false, false]);
  });
}
```

2023-08-31 18:16 UTC, hirokiterashima commented on src/app/teacher/teacher-run-list/teacher-run-list.component.ts
> +  }
Put the logic in TeacherRun?
```suggestion
  protected selectRunsOptionChosen(option: SelectRunsOption): void {
    const now = this.configService.getCurrentServerTime();
    this.filteredRuns.forEach((run: TeacherRun) => run.updateSelected(option, now));
    this.runSelectedStatusChanged();
  }
```

2023-08-31 18:16 UTC, hirokiterashima commented on src/app/teacher/teacher-run.ts
>  export class TeacherRun extends Run {
Move code for setting teacherRun.selected into this class?
```
  updateSelected(selectRunsOption: SelectRunsOption, currentTime: number): void {
    switch (selectRunsOption) {
      case 'ALL':
        this.selected = true;
        break;
      case 'NONE':
        this.selected = false;
        break;
      case 'COMPLETED':
        this.selected = this.isCompleted(currentTime);
        break;
      case 'RUNNING':
        this.selected = this.isActive(currentTime);
        break;
      case 'SCHEDULED':
        this.selected = this.isScheduled(currentTime);
        break;
    }
  }
```

2023-08-31 18:16 UTC, hirokiterashima commented on src/app/teacher/select-runs-controls/select-runs-controls.component.ts
> +  @Output() selectRunsOptionChosenEvent = new EventEmitter<string>();
Emit SelectRunsOptions enum class?
```suggestion
  @Output() selectRunsOptionChosenEvent = new EventEmitter<SelectRunsOption>();
```

SelectRunsOptions enum class definition:
```
export enum SelectRunsOption {
  All = 'ALL',
  None = 'NONE',
  Completed = 'COMPLETED',
  Running = 'RUNNING',
  Scheduled = 'SCHEDULED'
}
```

2023-08-31 18:16 UTC, hirokiterashima commented on src/app/teacher/select-runs-controls/select-runs-controls.component.ts
> +  }
Emit SelectRunsOption enum value?
```suggestion
  protected selectAllRunsCheckboxClicked(): void {
    this.selectRunsOptionChosenEvent.emit(
      this.selectedAllRuns || this.selectedSomeRuns ? SelectRunsOption.None : SelectRunsOption.All
    );
  }

  protected selectRunsOptionChosen(value: string): void {
    this.selectRunsOptionChosenEvent.emit(value as SelectRunsOption);
  }
```

2023-08-31 18:16 UTC, hirokiterashima commented on src/app/teacher/select-runs-controls/select-runs-controls.component.html
> +      <button mat-menu-item (click)="selectRunsOptionChosen('scheduled')" i18n>Scheduled</button>
Use enum values?
```suggestion
      <button mat-menu-item (click)="selectRunsOptionChosen('ALL')" i18n>All</button>
      <button mat-menu-item (click)="selectRunsOptionChosen('NONE')" i18n>None</button>
      <button mat-menu-item (click)="selectRunsOptionChosen('COMPLETED')" i18n>Completed</button>
      <button mat-menu-item (click)="selectRunsOptionChosen('RUNNING')" i18n>Running</button>
      <button mat-menu-item (click)="selectRunsOptionChosen('SCHEDULED')" i18n>Scheduled</button>
```

2023-09-07 17:08 UTC, hirokiterashima approved these changes
LGTM

2023-09-07 18:17 UTC, breity approved these changes
Looks good!

2023-09-18 20:54 UTC, merged

2023-09-18 20:56 UTC, hirokiterashima commented
:tada: This PR is included in version 5.112.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-Client/releases/tag/v5.112.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: