feat(Match): Implement component export for choice reuse
WISE-Community/WISE-Client pull request #1254
Opened 2023-05-11 19:29 UTC by geoffreykwan

## Changes

Match component export now properly exports data when a Match component can reuse choices.

## Test

- Create a Match component with choice reuse enabled as well as correctness and correct positions
- Generate some work for that Match component with choice reuse enabled
- Generate the Match component export
  - Classroom Monitor > Data Export view > Export Component Data > Find the Match component and click "All" button
- In the export, check
  - If a choice is in multiple buckets, those bucket names should show up in the cell separated by commas
  - Make sure the correctness value is correct when a choice is placed in multiple buckets based on this matrix below. The previous and next is in reference to when we loop through the buckets to check for correctness.
Examples
    - If choice "Apple" was placed in bucket "A", which is correct, and also placed in bucket "Wildcard", which is also correct, then we would say the previous value was 1 (because it was correct in bucket "A") and the new value is 1 (because it was correct in bucket "Wildcard") and the merged value is 1.
    - If choice "Apple" was placed in bucket "A", which is correct, and also placed in bucket "B", which is incorrect, then we would say the previous value was 1 (because it was correct in bucket "A") and the new value is 0 (because it was incorrect in bucket "B") and the merged value is 0.
```
e = empty
0 = incorrect
1 = correct
2 = correct bucket but incorrect position

       Previous Value
       e 0 1 2
      --------
N  0 | 0 0 0 0
e  1 | 1 0 1 2
w  2 | 2 0 2 2

V
a
l
u
e
```
- Make sure Match component export without choice reuse still works properly

Closes #1251

2023-05-11 23:08 UTC, hirokiterashima requested changes
Export seems to work as described.

I added some code comments inline.

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +    newValue: any
```suggestion
    newValue: number
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +    item: any
```suggestion
    bucket: Bucket,
    item: Choice
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +  private setCorrectnessValueForChoiceReuse(row: any[], columnNameToNumber: any, item: any): void {
```suggestion
  private setCorrectnessValueForChoiceReuse(row: any[], columnNameToNumber: any, item: Choice): void {
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +    } else if (this.eitherValuesAreX(previousValue, newValue, 0)) {
Do this check inline and remove extra function call?
```suggestion
    } else if ([previousValue, newValue].includes(0))) {
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +    } else if (this.eitherValuesAreX(previousValue, newValue, 2)) {
Do this check inline and remove extra function call?
```suggestion
    } else if ([previousValue, newValue].includes(2))) {
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
>    }
Remove function?
```suggestion
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/components/match/bucket.ts
> +  items?: Choice[];
Are there buckets that will never have any items?
```suggestion
  items: Choice[];
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +    }
Use ternary expression to simplify block
```suggestion
    row[columnNameToNumber[item.id]] =
      row[columnNameToNumber[item.id]] == null || row[columnNameToNumber[item.id]] === '' ?
        this.getBucketValueById(component, bucket.id) :
        `${row[columnNameToNumber[item.id]]}, ${this.getBucketValueById(component, bucket.id)}`; 
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +  }
Make this into a specific function to test if both values are 1 (correct) instead?
```suggestion
  private bothValuesAreCorrect(value1: number, value2: number): boolean {
    return value1 === 1 && value2 === 1;
  }
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +    } else if (this.bothValuesAreX(previousValue, newValue, 1)) {
Make this check more clear by stating that we're checking if both are correct?
```suggestion
    } else if (this.bothValuesAreCorrect(previousValue, newValue)) {
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +    newValue: any
```suggestion
    newValue: number
```

2023-05-11 23:08 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/data-export/data-export.component.ts
> +  private setBucketValueWithAppending(
This "WithAppending" part of the function name is a bit confusing. How about just ```setBucketValue()```?
```suggestion
  private setBucketValue(
```

2023-05-15 21:58 UTC, geoffreykwan commented on src/assets/wise5/components/match/bucket.ts
> +  items?: Choice[];
The bucket object in the authored content does not have items.

2023-05-16 01:08 UTC, hirokiterashima approved these changes
LGTM

2023-05-17 15:01 UTC, merged