feat(FeedbackRule): New accumulatedIdeaCount[LessThan|Equals|MoreThan] token
WISE-Community/WISE-Client pull request #1258
Opened 2023-05-15 00:02 UTC by hirokiterashima

## Changes
- FeedbackRuleEvaluator now takes in an array of CRaterResponses instead of just the latest
- DialogGuidanceStudent now passes in all CRaterResponses to the FeedbackRuleEvaluator
- OpenResponse and DynamicPrompt still passes in an array containing just the latest CRaterResponse
- Clean up code
   - Define CRaterResponses interface

## Test
-

Closes #1257

2023-05-15 16:26 UTC, geoffreykwan requested changes
Functionality works well.

2023-05-15 16:26 UTC, geoffreykwan commented on src/assets/wise5/services/studentDataService.ts
> +import { DialogResponse } from '../components/dialogGuidance/DialogResponse';
We can remove these unused imports.

2023-05-15 16:26 UTC, geoffreykwan commented on src/assets/wise5/components/common/cRater/CRaterResponses.ts
> +}
Having this interface name be plural is slightly confusing. Would it be better to name it RawCRaterResponse or CRaterRawResponse or something like that?

2023-05-15 16:26 UTC, geoffreykwan commented on src/assets/wise5/components/common/feedbackRule/feedback-rule-help/feedback-rule-help.component.html
> +    </tr>
This shows up in the Help section for Open Response and Dynamic Prompt even though it doesn't work in those places. Should we have it not show up in those places or add a footnote or something?

2023-05-15 18:45 UTC, hirokiterashima commented
@geoffreykwan made changes. PTAL

2023-05-15 21:20 UTC, geoffreykwan approved these changes
Looks good.

I think the Note wording might be a little better if it was
"Note: this term currently only works in the Dialog Guidance component."

2023-05-16 16:55 UTC, breity approved these changes
Looks good. 👍

2023-05-17 19:43 UTC, merged