feat(Password): Allow special characters in password
WISE-Community/WISE-Client pull request #1402
Opened 2023-09-05 16:53 UTC by geoffreykwan

## Changes

- Allow these symbols to be used in a password !@#$%^&*
- Passwords now require a letter, number, symbol, and to be at least 8 characters (no longer require uppercase letter but they may still be used)
- Added password strength indicator
- Added visual password requirement validator

## Test

Make sure setting a password in these locations still works properly
- Create teacher account
- Create student account
- Forgot teacher password
- Forgot student password
- User change password
- Teacher change student password

Closes #1049

2023-09-07 20:20 UTC, hirokiterashima requested changes
Feature works great. I have some comments/questions:

- Do we want to require symbols? This would make passwords more difficult to remember, especially students.
- Always showing password strength indicator by default when the pages load feels a bit off because I haven't typed in anything yet. Should it show up once you start typing a password?
- And also maybe @breity can style the indicator a bit to fit into the page better and ensure contrast (a11y)?
- Change success message from "Password Changed" to "Successfully changed password" to make it more friendly?
- Code improvements
   - See inline comments
   - See if you can remove all duplications? 
   - For the new tests in this change set
      - change it('should disable ...') to it('disables ...')  https://github.com/CareMessagePlatform/jasmine-styleguide#speak-human?
      - try to change test blocks to follow Arrange-Act-Assert pattern (https://github.com/CareMessagePlatform/jasmine-styleguide#arrange-act-assert) ?

2023-09-07 20:20 UTC, hirokiterashima commented on src/app/common/password-helper.ts
> +  error: any,
type PasswordErrors?

2023-09-07 20:20 UTC, hirokiterashima commented on src/app/forgot/student/forgot-student-password-change/forgot-student-password-change.component.ts
>    private changePasswordError(error: any): void {
type PasswordErrors?

2023-09-07 20:20 UTC, hirokiterashima commented on src/app/forgot/teacher/forgot-teacher-password-change/forgot-teacher-password-change.component.ts
>    private changePasswordError(error: any): void {
type PasswordErrors?

2023-09-07 20:20 UTC, hirokiterashima commented on src/app/modules/shared/edit-password/edit-password.component.spec.ts
> +  return typeof arg === 'string' ? { error: { messageCode: arg } } : { error: arg };
Reduce duplication? Do you need generateSuccessObservable() and generateErrorObservable(), or can do you it with a ternary in generateObservableResponse()?

```
function generateObservableResponse(arg: string | any, isSuccess: boolean): Observable<any> {
  return new Observable((observer) => {
    observer.next(isSuccess ? generateSuccessResponseValue(arg) : generateErrorResponseValue(arg));
    observer.complete();
  });
}
```

2023-09-07 20:20 UTC, hirokiterashima commented on src/app/password/new-password-and-confirm/new-password-and-confirm.component.spec.ts
> +  });
Change block to follow Arrange-Act-Assert pattern (https://github.com/CareMessagePlatform/jasmine-styleguide#arrange-act-assert)
Add beforeEach() to call the action (```await newPasswordAndConfirmHarness.setNewPassword(password);```), and then check the state inside the it() (```await checkPasswordRequirements(passwordErrors);```).

2023-09-07 20:20 UTC, hirokiterashima commented on src/app/password/new-password-and-confirm/new-password-and-confirm.harness.ts
> +  async isMissingRequirement(
private?

2023-09-11 21:41 UTC, hirokiterashima reviewed
Can we try not to introduce these new duplications?
1. generateSuccessObservable() and generateErrorObservable()
2. setNewPassword() and setConfirmNewPassword()

2023-10-09 19:17 UTC, hirokiterashima reviewed
New changes look good.

We still need to discuss/address these:
- Always showing password strength indicator by default when the pages load feels a bit off because I haven't typed in anything yet. Should it show up once you start typing a password?
- Maybe @breity can style the indicator a bit to fit with the rest of the page better and ensure that a11y standards are met (e.g. has good contrast)?

2023-10-13 22:53 UTC, geoffreykwan commented
@breity I needed to add this to new-password-and-confirm.component.scss in order to set the width of the menu since the default width caused some text to wrap. Is there a better way to do this without ng-deep?

```
::ng-deep .mat-mdc-menu-panel {
  max-width: none !important;
}
```

2023-10-16 23:57 UTC, breity commented
I removed the ng-deep requirement by setting view encapsulation to none for the component. Just need to be careful to make sure component styles don't modify any styles used elsewhere in the app when doing so.

I also cleaned up the styles/layout a bit and address a11y contrast. I removed the changing color for the text indicating password strength ("Very Weak", "Weak", ...) because it's difficult to find colors with sufficient contrast in the yellow and orange ranges unless they're pretty dark. So the text indicating strength is always the default text color. I think the colors on the strength meter combined with text itself works fine.

2023-10-18 00:30 UTC, hirokiterashima approved these changes
New popup behavior looks good.

Can you add margin or padding to the text in the popup? Everything looks very close to the edge of the popup, which makes it a bit hard to read:
<img width="324" alt="image" src="https://github.com/WISE-Community/WISE-Client/assets/119416/32c42fb7-c4dd-436c-be9b-2342fdebc80e">

2023-10-22 17:44 UTC, merged