feat(Question Bank): Click question to add to student response input
WISE-Community/WISE-Client pull request #1416
Opened 2023-09-12 16:27 UTC by geoffreykwan

## Changes

- Allow students to click on questions in the question bank to add the question text into the response input. The student can then modify the question if they would like before they submit it.
- Allow authors to enable and disable this feature
- Allow authors to change the name of the question bank
- After a student uses a question, indicate that the question has been used
- Store which question was used in the student response
- When questions are authored, they should now have a unique id
  - New Question Bank content is marked as version 2 which contains question objects that have an id and text field
  - Old Question Bank content contains question strings

## Test

As a teacher
1. Create a new Peer Chat component
2. Enable the Question Bank in the Peer Chat
3. Set a Custom Label for the Question Bank
4. Enable Student Click To Add
5. Set a Reference Component
6. Set Grouping Logic
7. Add some Question Bank Rules

As a student
1. Go to the Peer Chat step and make sure the Question Bank shows up and the questions are clickable
2. Click on a question to add it to the student response input
3. Click "Send" to submit the response. The question in the question bank should show that it has been used.
4. Click on a question to add it to the student response input
5. Delete the question from the student response input. Type something else and submit the response. The question should not show that it has been used.
6. Leave the step
7. Go back to the Peer Chat step. The questions should show which ones have been used.

Make sure old Peer Chat Question Bank still works as before for teacher and student.

Closes #1413

2023-09-13 22:00 UTC, breity requested changes
Functionality looks great. I made some style changes and added some text for screen readers.

I found one minor bug. To reproduce:
- Click on one of the question buttons to add to response input
- Delete the text in the response input.
- Click on the same question again.

The question won't be added to the response input.

2023-09-14 15:42 UTC, hirokiterashima requested changes
Looking good. I have some comments:
- It would be nice to explain what the "Enable Student Click To Add" option is, or make it more obvious, like "Student can click on items to add to peer chat"
- Are we assuming that they always start by choosing a question bank item first? If I write something and then choose a question, it overwrites what I typed. Should the questions append instead of overwriting? 
- Grading view is not working for me. I see this and an error in the console:
<img width="1276" alt="Screenshot 2023-09-13 at 2 54 04 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/ccbd95c8-6508-4c58-bd66-dae1dabc2e31">
<img width="618" alt="Screenshot 2023-09-13 at 2 54 11 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/0650c692-dcc5-4e8d-8242-dab8d9097a7c">

- Rename ```questionClicked()``` to ```addQuestionToChat()``` or something similar?

2023-09-14 21:50 UTC, geoffreykwan commented
I changed the component content field from "clickToAddEnabled" to "clickToUseEnabled" so you'll need to check the "Student can click questions to use in Peer Chat" check box in the Peer Chat Question Bank authoring to enable the feature again.

2023-09-18 16:38 UTC, breity approved these changes
Functionality looks great. 👍 

I updated the language slightly for the label for the authoring tool setting ("click" -> "select") and the student overwrite confirmation for clarity/brevity.

2023-09-18 17:30 UTC, hirokiterashima approved these changes
Looks good. I added minor code improvement suggestions to consider before merging.

2023-09-18 17:30 UTC, hirokiterashima commented on src/assets/wise5/components/peerChat/peer-chat-question-bank/question-bank-helper.ts
> +    .filter((componentState) => componentState.studentData.questionId != null)
Combine into one filter to remove extra loop?

2023-09-18 17:30 UTC, hirokiterashima commented on src/assets/wise5/components/peerChat/peer-chat-student/peer-chat-student.component.ts
> +        $localize`Are you sure you want to put this question into your input box? The question will overwrite the current text in your input box.`
Should we use the term "question" here, or use something more generic, like "item"? Some authors may rename "Question Bank" to "Prompt Bank".

2023-09-18 17:30 UTC, hirokiterashima commented on src/assets/wise5/components/peerChat/peer-chat-message-input/peer-chat-message-input.component.ts
> +  placeCursorAtEndOfMessageText(event: any): void {
private?

2023-09-18 17:30 UTC, hirokiterashima commented on src/assets/wise5/components/peerChat/peer-chat-message-input/peer-chat-message-input.component.ts
> +  onFocus(event: any): void {
protected?

2023-09-18 17:30 UTC, hirokiterashima commented on src/assets/wise5/components/peerChat/peer-chat-message-input/peer-chat-message-input.component.ts
> +  @Output('onSubmit') submit: EventEmitter<string> = new EventEmitter<string>();
add private/protected as appropriate?

2023-09-18 17:30 UTC, hirokiterashima commented on src/app/authoring-tool/edit-question-bank/edit-question-bank.component.ts
> +  subscriptions: Subscription = new Subscription();
Add private/protected as appropriate?

2023-09-18 17:30 UTC, hirokiterashima commented on src/app/authoring-tool/edit-question-bank-rules/edit-question-bank-rules.component.spec.ts
> +    it('should add new question to rule', () => {
"adds new question to rule"? Remove "should".

2023-09-18 18:50 UTC, geoffreykwan commented on src/assets/wise5/components/peerChat/peer-chat-message-input/peer-chat-message-input.component.ts
> +  @Output('onSubmit') submit: EventEmitter<string> = new EventEmitter<string>();
@Input() and @Output() variables should be public right?

2023-09-18 19:04 UTC, hirokiterashima commented on src/assets/wise5/components/peerChat/peer-chat-message-input/peer-chat-message-input.component.ts
> +  @Output('onSubmit') submit: EventEmitter<string> = new EventEmitter<string>();
Ah, right- in this case, it's public. 

I just wanted to make sure that we add modifiers to all new field variables, where appropriate.

2023-09-18 22:03 UTC, merged

2023-09-18 22:04 UTC, hirokiterashima commented
:tada: This PR is included in version 5.113.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-Client/releases/tag/v5.113.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: