refactor(NodeAuthoring): Extract EditNodeTitleComponent
WISE-Community/WISE-Client pull request #1537
Opened 2023-11-27 19:17 UTC by hirokiterashima

## Changes
- Componentize EditNodeTitleComponent (used to be a part of NodeAuthoringComponent) 
- Change input label for groups from "Activity Title" to "Lesson Title"
- Add tests

## Test
- Lesson title and step title can be edited and saved as before
   - Lesson title input label should say "Lesson title [position]:"
   - Step title input label should say "Step title [position]:"

2023-11-28 16:53 UTC, geoffreykwan requested changes
Functionality mostly works.

2023-11-28 16:53 UTC, geoffreykwan commented on src/assets/wise5/authoringTool/node/edit-node-title/edit-node-title.component.html
> +    [ngModelOptions]="{ debounce: 500 }"
The debounce doesn't seem to work. Maybe try performing the debounce like we do in [label-authoring.component.ts](https://github.com/WISE-Community/WISE-Client/blob/92c3c16e0fdd0c5dffaf6253c1d366440be0f63a/src/assets/wise5/components/label/label-authoring/label-authoring.component.ts#L36-L40).

2023-11-28 16:53 UTC, geoffreykwan commented on src/assets/wise5/authoringTool/node/edit-node-title/edit-node-title.component.spec.ts
> +  it('should show step position and title', () => {
Change 'should show' to 'shows'.

2023-11-28 19:25 UTC, hirokiterashima commented
The input wasn't debouncing in the develop branch. Since this is a refactoring PR, I removed the debounce ngModelOption instead of trying to get it to work again. Let's discuss as a group if we want to add debounce back for this input. If we do, we can do that in a future task. 

PTAL

2023-11-29 15:51 UTC, geoffreykwan approved these changes
Looks good.

2023-11-29 17:36 UTC, merged

2023-11-30 17:49 UTC, geoffreykwan commented
:tada: This PR is included in version 5.126.2 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-Client/releases/tag/v5.126.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: