feat(Multiple Languages): Show ProjectLanguageChooser in AT
WISE-Community/WISE-Client pull request #1550
Opened 2023-12-05 23:27 UTC by hirokiterashima

## Note
Remember to use the ```[field].i18n = { id: "abc123", "modified": 123 }``` project format for this PR and all future PR's.

## Changes
- Change ProjectLanguageChooserComponent so we can use it in the VLE and the AT
   - Take in ```ProjectLocale``` as ```@Input``` 
   - Emit selected ```Language``` as ```@Output```
   - Move to common folder
- Display ProjectLanguageChooserComponent in the AT's TopBarComponent if unit has translations
   - Update available language options when author changes them in the Project Info view

## Test AT
- ProjectLanguageChooserComponent displays supported languages iff unit has translations
- Editing language options in the Project Info view updates the ProjectLanguageChooserComponent's available options

*Note: we don't do anything when we switch language option in the ProjectLanguageChooserComponent atm. We'll handle that in a future PR.

## Test Student VLE
- Switching between translations work as before. While logged in as a student or previewing a unit, test that:
   - Languages drop-down appears only if the unit has at least 1 supported locale
   - Switching between the language options immediately translates elements of the page that have translations
      - Test everywhere: unit plan, step select drop down, unit title
      - Elements that don't have translations appear in default locale
      - You can switch back to default locale

2023-12-06 16:02 UTC, geoffreykwan requested changes
Mostly works but I found one issue.

In the Authoring Tool, if you have set the language in the top bar to one of the additional languages and then go to the Unit Info view and change the default language or add/delete an additional language, the language in the top bar changes back to the default language.

I think how we should handle this is if the author is in the Unit Info view and changes the default language or additional languages, the top bar language should not change. The top bar language should only change to the default language if the language that is currently selected in the top bar is removed from the additional languages.

2023-12-06 21:34 UTC, hirokiterashima commented
@geoffreykwan Good catch. We now set selected language to the default language only when the previously-selected option is no longer available (i.e., removed by author), or this is the first time that the component is displayed. PTAL.

2023-12-07 17:09 UTC, geoffreykwan approved these changes
Looks good. I have some minor suggestions.

2023-12-07 17:09 UTC, geoffreykwan commented on src/app/common/project-language-chooser/project-language-chooser.component.ts
> +      );
Can this be changed to 
```
this.selectedLanguage = this.projectLocale.getDefaultLanguage();
```
now that there is a isSameLanguage() function that is used in [compareWith]?

2023-12-07 17:09 UTC, geoffreykwan commented on src/app/common/project-language-chooser/project-language-chooser.component.spec.ts
> +});
Instead of 
```
await options[1].click();
```
you could do
```
const selectHarness = await loader.getHarness(MatSelectHarness);
await selectHarness.clickOptions({ text: 'Japanese' });
```
and then you can get the selected value by doing
```
expect(await selectHarness.getValueText()).toEqual('Japanese');
```

2023-12-07 17:09 UTC, geoffreykwan commented on src/app/common/project-language-chooser/project-language-chooser.component.spec.ts
> +}
You can do this to get the first MatSelectHarness without having to get all of them and then getting the first one from the array.
```
const selectHarness = await loader.getHarness(MatSelectHarness);
```

2023-12-07 17:09 UTC, geoffreykwan commented on src/app/common/project-language-chooser/project-language-chooser.component.spec.ts
> +  it('shows available languages and selects the default language', async () => {
Should this be wrapped in a describe that describes the initial state like ```describe('when the language chooser is first loaded')``` or something.

2023-12-07 17:09 UTC, geoffreykwan commented on src/app/common/project-language-chooser/project-language-chooser.component.spec.ts
> +  it('keeps selected language option when language option changes', async () => {
Should this be wrapped in a describe that describes the action like ```describe('when the language options change')``` or something.

2023-12-12 19:53 UTC, hirokiterashima commented on src/app/common/project-language-chooser/project-language-chooser.component.ts
> +      );
Yes, this works. I changed it.

2023-12-12 19:56 UTC, hirokiterashima commented on src/app/common/project-language-chooser/project-language-chooser.component.spec.ts
> +});
Good suggestion. Made the code easier to understand.

2023-12-12 19:56 UTC, hirokiterashima commented on src/app/common/project-language-chooser/project-language-chooser.component.spec.ts
> +}
Good suggestion. Made the code easier to understand.

2023-12-12 19:58 UTC, merged