feat(Component Info): Allow multiple examples per component type
WISE-Community/WISE-Client pull request #1566
Opened 2023-12-15 19:40 UTC by geoffreykwan

## Changes
-

## Test
-

Closes #1519

2023-12-19 00:03 UTC, breity requested changes
Looks good. 👍 

I updated styles some to better distinguish between description and example content.

One minor issue: The multiple choice example that allows multiple selection doesn't seem to preview properly. Clicking on any one of the options doesn't toggle the checkbox. If you switch to another component type and then come back to the multiple choice component, the multiple choice preview is broken. Switching to another component and going back a second time renders the multiple choice preview again and will show the multiple selected options.

2023-12-19 17:16 UTC, geoffreykwan commented
The problems with Multiple Choice preview should be fixed in #1565.

2023-12-20 17:43 UTC, breity approved these changes

2023-12-20 21:59 UTC, merged

2023-12-20 22:03 UTC, geoffreykwan commented
:tada: This PR is included in version 5.128.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-Client/releases/tag/v5.128.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: