feat(Authoring): Click lesson bar to expand and collapse steps
WISE-Community/WISE-Client pull request #1629
Opened 2024-02-13 16:26 UTC by geoffreykwan

## Changes
- Clicking the lesson bar now expands and collapses the steps in the lesson
- Added a button to enter the lesson authoring view where you can change the lesson title
- When a lesson has no steps, display a message

## Test
- Make sure clicking on a lesson expands and collapses the steps in the lesson
- Make sure the lesson edit button brings you to the edit lesson view
- When a lesson has no steps, make sure it displays the message "This lesson has no steps"

Closes #1628

2024-02-13 22:16 UTC, hirokiterashima requested changes
Here's what we discussed today:

- Change the edit lesson icon from wrench to pencil, and only show it if the lesson is expanded, or on mouseover
- Tooltip on the lesson should say “Click to expand/collapse lesson"
- Change the lesson's background-color behavior to match that of the components in node authoring
   - Add background-color to the entire lesson (all the way out to the edges) when the lesson is collapsed
   - Don’t add background-color when the lesson is expanded

2024-02-13 23:19 UTC, geoffreykwan commented
I've made the requested changes.

2024-02-14 16:06 UTC, hirokiterashima approved these changes
LGTM. Should the tooltip for the pencil icon say "Edit Lesson" (instead of simply "Edit") to be more clear?

2024-02-14 16:45 UTC, geoffreykwan commented
Yea it's probably better if it says "Edit lesson". I've made the change.

2024-02-14 16:45 UTC, merged

2024-02-14 16:49 UTC, geoffreykwan commented
:tada: This PR is included in version 5.134.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-Client/releases/tag/v5.134.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: