feat(Authoring): Add move, copy, and delete buttons to all steps
WISE-Community/WISE-Client pull request #1633
Opened 2024-02-14 22:39 UTC by geoffreykwan

## Changes
- Added move, copy, and delete buttons to the steps
- The buttons only show up when mousing over the step

## Test
Make sure the
- move button moves the step
- copy button copies the step and puts the new step right after the original step
- delete button deletes the step

Closes #1631

2024-02-15 00:38 UTC, hirokiterashima requested changes
This is a lot of changes for me to review at once. Can you break it up into smaller PR's? Maybe we should create a feature branch?

2024-02-16 16:16 UTC, geoffreykwan commented
I removed the move and copy buttons.

2024-02-16 18:42 UTC, hirokiterashima requested changes
Looking good.

Here's what we discussed today:
1. When the "Delete step" tooltip is shown, hide the "Click to enter step" tooltip.
2. Allow authors to delete lessons. The delete icon should appear to the right of the edit icon.

I added inline comments for code improvement suggestions.

2024-02-16 18:42 UTC, hirokiterashima commented on src/assets/wise5/authoringTool/project-authoring-step/project-authoring-step.component.ts
> +  @Output() deleteEvent: EventEmitter<any> = new EventEmitter<any>();
Is this line necessary? Looks like it's not being used.

2024-02-16 18:42 UTC, hirokiterashima commented on src/assets/wise5/authoringTool/project-authoring-step/project-authoring-step.component.ts
> +  protected delete(event: any): void {
Add type
```suggestion
  protected delete(event: Event): void {
```

2024-02-16 22:04 UTC, geoffreykwan commented
I fixed the tooltips and cleaned up the code. We can add the delete lesson button in another issue.

2024-02-20 18:02 UTC, hirokiterashima approved these changes
LGTM.

In the future, it would be good if you could also say why you decided to postpone adding the Delete Button to lesson, because this is different from what we discussed together. Was it because it's too much work, will increase the review scope by a lot, etc.

2024-02-20 21:45 UTC, merged

2024-02-20 21:49 UTC, geoffreykwan commented
:tada: This PR is included in version 5.135.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-Client/releases/tag/v5.135.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: