feat(Authoring): Implement add step button menu next to all steps
WISE-Community/WISE-Client pull request #1662
Opened 2024-02-27 23:44 UTC by geoffreykwan

## Changes
- Added an add button next to all the steps in the project view. This button only shows up when hovering over that step.
- Clicking on the add button will open a menu that has the options "Add Step Before" and "Add Step After"
- Clicking on either of the options will create a new step named "New Step"
- The new step will have no components

## Test
- Try adding a new step using the new add step button menu
- Try adding a step before the first step in a lesson
- Try adding a step before a step that is not the first step in a lesson
- Try adding a step after a step

Closes #1661

2024-02-28 20:28 UTC, hirokiterashima requested changes
Looks good.

Here are the changes that we discussed today:
1. Always show the "Add step button" instead of just on hover.
2. Add "Add step button" to empty lesson, next to the text "This lesson has no steps"

Also- do we want to allow authors to add steps without going through the "Add step wizard"? This would be a new behavior. I'm wondering if we should make this merge to a new feature branch instead of into develop. For the next task in this feature branch, we can connect this new "Add step button" to go to the "Add step wizard". What do you think?

2024-02-28 23:04 UTC, geoffreykwan commented
I've made the two changes. I think we can merge this into develop and make a new PR for the add step wizard. Authors can still use the add new step button at the top of the screen for now.

2024-02-29 01:27 UTC, hirokiterashima commented
New changes look good. After further testing, I found possible issues adding steps in a branch activity.

1. The newly added step does not have the same color as the other steps in the same branch path. Here, I added a step after step 1.3A:
<img width="1250" alt="Screenshot 2024-02-28 at 5 18 24 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/739449de-91b3-43ff-8d7f-a70964669309">

The new step 1.4A should have the green color.


2. When I add a step before the first step in a branch path, the behavior is not what I expect:

Before adding a step before step 1.2A:
<img width="792" alt="Screenshot 2024-02-28 at 5 13 49 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/ae6ecc2d-7ee5-4b45-920e-d2ebc5a79f2e">

After:
<img width="796" alt="Screenshot 2024-02-28 at 5 13 58 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/9e92e14f-efea-43ec-8a8c-8241209eaf1f">

In this scenario, I expected the new step to be the new step 1.2A. But as you can see, the new step became a branch point. If this is hard to fix, maybe we can disable the "add step before" option to the first step in a branch path?

2024-02-29 01:28 UTC, hirokiterashima commented
New changes look good. After further testing, I found possible issues adding steps in a branch activity.

1. The newly added step does not have the same color as the other steps in the same branch path. Here, I added a step after step 1.3A:
<img width="1250" alt="Screenshot 2024-02-28 at 5 18 24 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/739449de-91b3-43ff-8d7f-a70964669309">

The new step 1.4A should have the green color.


2. When I add a step before the first step in a branch path, the behavior is not what I expect:

Before adding a step before step 1.2A:
<img width="792" alt="Screenshot 2024-02-28 at 5 13 49 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/ae6ecc2d-7ee5-4b45-920e-d2ebc5a79f2e">

After:
<img width="796" alt="Screenshot 2024-02-28 at 5 13 58 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/9e92e14f-efea-43ec-8a8c-8241209eaf1f">

In this scenario, I expected the new step to be the new step 1.2A. But as you can see, the new step became a branch point. If this is hard to fix, maybe we can disable the "add step before" option to the first step in a branch path?

2024-02-29 21:46 UTC, geoffreykwan commented
I've fixed the background color issue and disabled the "add step before" button for steps that are the first step in a branch path.

2024-03-01 15:53 UTC, hirokiterashima approved these changes
LGTM

2024-03-01 19:36 UTC, merged