feat(Tag): Implement manage tags dialog
WISE-Community/WISE-Client pull request #1693
Opened 2024-03-14 19:47 UTC by geoffreykwan

## Changes
- Implemented manage tags dialog
- Tag text can now be edited

## Test
- 
- In the Class Schedule view, select some units by clicking on their checkbox
- Click the "Apply Tags" button
- Click the "Manage Tags" menu item
- Change the text for a tag. The tag text should immediately update in the "Apply tags" menu but not in the unit cards. I'll fix the updating in the unit cards in another PR.

2024-03-15 18:39 UTC, hirokiterashima requested changes
Functionality works as described. I have a few comments:

1. We discussed using a snack bar to indicate that the change has been saved.
2. I added some code change suggestions inline.

I'm also wondering if we should split up the TagService to StudentTagService and UserTagService. It looks like there are two different kinds of tags right now, and handling them both in TagService is confusing. This refactoring can be done in a separate PR. Let's discuss how best to proceed.

2024-03-15 18:39 UTC, hirokiterashima commented on src/app/teacher/apply-tags-button/apply-tags-button.component.ts
> +    });
Does this need to be unsubscribed in ```ngOnDestroy()```? Also, would ```updatedTag``` be a better name here?

2024-03-15 18:39 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.ts
> +    this.tagService.retrieveUserTags().subscribe((tags: Tag[]) => {
unsubscribe in onDestroy()?

2024-03-15 18:39 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.ts
> +  inputChanged: Subject<string> = new Subject<string>();
protected?

2024-03-15 18:39 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.ts
> +  inputChangedSubscription: Subscription;
private?

2024-03-15 18:39 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.ts
> +        this.updateTag(tag);
Call service function directly and remove need to define a new function?
```suggestion
        this.tagService.updateTag(tag);
```

2024-03-15 18:39 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.html
> +          (ngModelChange)="inputChanged.next({ tag: tag, text: $event })"
```ManageTagsDialogComponent.inputChanged``` has type ```Subject<string>```, but here we're passing in an object. What should it be?

2024-03-15 18:39 UTC, hirokiterashima commented on src/assets/wise5/services/tagService.ts
> +  }
Do we need to return a Subscription? It looks like we don't do anything with it?
```suggestion
  updateTag(tag: Tag): void {
    this.http.put<Tag>(`/api/user/tag/${tag.id}`, tag).subscribe((tag) => {
      this.tagChangedSource.next(tag);
    });
  }
```

The other option is to return an Observable<Tag> and subscribe in the component.
```
  updateTag(tag: Tag): Observable<Tag> {
    return this.http.put<Tag>(`/api/user/tag/${tag.id}`, tag).pipe(
      tap((tag) => {
        this.tagChangedSource.next(tag);
      })
    );
  }
```

2024-03-18 15:54 UTC, geoffreykwan commented
Ok, I've made the changes.

2024-03-20 20:59 UTC, hirokiterashima approved these changes
LGTM

In ManageTagsDialogComponent, 
```protected inputChanged: Subject<string> = new Subject<any>();```
should be 
```protected inputChanged: Subject<any> = new Subject<any>();```
?

2024-03-21 18:52 UTC, merged