chore(Application) Upgrade to Angular v17
WISE-Community/WISE-Client pull request #1740
Opened 2024-04-17 18:53 UTC by hirokiterashima

## Changes
- Upgrade Angular version from 16 to 17
   -  Revert to using original ```angular-password-strength-meter``` dependency (before: we built and deployed our own ```@wise-community/angular-password-strength-meter```
   - Change instances where we were calling ```mutate()``` on signals, as this is no longer supported in Angular 17. Instead, we call ```update()```. If it's an object or array that we're updating, we need to make sure that we're returning a new reference for the change to propagate.
   - Update tests

## Test
- Everything works as before, in particular:
   - Password strength meter works as before in creating new account and updating existing account's password
   - Selecting/unselecting single/multiple/none units in Unit Library
   - Archiving/unarchiving unit
   - Authoring tool 
      - expand all/collapse all lessons and components
      - selecting steps/components and moving/deleting/copying them

Closes #

2024-04-18 17:03 UTC, geoffreykwan requested changes
I came upon this weird behavior in the VLE.

1. Go to the Authoring Tool to author a unit
2. Create a step that contains all item types
3. Create another step after it that contains one item like Open Response
4. Preview the unit
5. Go to the first step
6. Go to the second step and it will show a bunch of items when it should only show the Open Response item

2024-04-18 17:03 UTC, geoffreykwan commented on src/app/modules/library/personal-library/personal-library.component.ts
> +import { copy } from '../../../../assets/wise5/common/object/object';
Unused import can be deleted.

2024-04-19 01:49 UTC, hirokiterashima commented on src/app/modules/library/personal-library/personal-library.component.ts
> +import { copy } from '../../../../assets/wise5/common/object/object';
done

2024-04-19 01:51 UTC, hirokiterashima commented
@geoffreykwan Good catch. This was due to an Angular Flex Layout issue. In order to work with Angular 17, we need to declare the class before we can add/remove it to an element. I fixed this in the discussion component and the About us page. Both were not displaying correctly due to this issue.

2024-04-19 18:51 UTC, geoffreykwan approved these changes
Looks good.

2024-04-22 05:44 UTC, breity approved these changes
LGTM.

2024-04-25 21:09 UTC, merged

2024-04-29 21:15 UTC, geoffreykwan commented
:tada: This PR is included in version 5.153.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-Client/releases/tag/v5.153.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: