feat(Teacher): Implement unit tagging
WISE-Community/WISE-Client pull request #1813
Opened 2024-05-23 19:21 UTC by geoffreykwan

## Changes
-

## Test
-

Closes #1686

2024-05-28 15:48 UTC, hirokiterashima requested changes
The functionality mostly works. 

It looks like the number of tags in the message when you try to delete a tag is off. In the screenshot below, you can see that I have "tag3" on a unit, but the cofirmation message says "0" I think it may not be counting the tags that are on the units (as opposed to run units).

<img width="300" alt="Screenshot 2024-05-24 at 3 30 00 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/f2355334-f845-4d31-9ba6-b1f66459debd">


I also added some code cleaning suggestions inline. 

Lastly, maybe we should also apply the code cleaning conventions for at least the new standalone components, like alphabetizing (imports -> selector -> standalone...), rename "styleUrls" -> "styleUrl", self-closing tags, and such?

2024-05-28 15:48 UTC, hirokiterashima commented on src/app/teacher/select-tags/select-tags.component.ts
> +  imports: [CommonModule, MatDividerModule, SearchBarComponent, SharedModule]
Should we import SharedModule here? It includes things that we don't use like UnlinkGoogleAccountConfirmComponent and UnlinkGoogleAccountPasswordComponent. Instead, can we import only the classes that we need?

2024-05-28 15:48 UTC, hirokiterashima commented on src/app/teacher/apply-tags-button/apply-tags-button.component.ts
> +    SharedModule
Should we import SharedModule here? It includes things that we don't use like UnlinkGoogleAccountConfirmComponent and UnlinkGoogleAccountPasswordComponent. Instead, can we import only the classes that we need?

2024-05-28 15:48 UTC, hirokiterashima commented on src/app/teacher/teacher.module.ts
> +  MatChipsModule,
Is this import necessary?

2024-05-28 15:48 UTC, hirokiterashima commented on src/app/modules/library/select-all-items-checkbox/select-all-items-checkbox.component.spec.ts
> +      imports: [MatCheckboxModule, MatTooltipModule, SelectAllItemsCheckboxComponent]
Are MatCheckboxModule and MatTooltipModule needed?

2024-05-28 15:48 UTC, hirokiterashima commented on src/app/teacher/color-chooser/color-chooser.component.spec.ts
> +      imports: [ColorChooserComponent, CommonModule, MatChipsModule]
Are CommonModule and MatChipsModule needed?

2024-05-28 15:48 UTC, hirokiterashima commented on src/app/teacher/edit-tag/edit-tag.component.spec.ts
> +        MatSnackBarModule
This this import needed?

2024-05-28 15:48 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.spec.ts
> +        MatSnackBarModule,
Is this import needed?

2024-05-28 15:48 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.ts
> +    private projectTagService: ProjectTagService
alphabetize?

2024-05-29 23:34 UTC, geoffreykwan commented
I've fixed the bug and made all the changes.

Make sure to get the latest from the WISE-API branch issue-259-implement-unit-tagging for the fix to work.

2024-06-17 21:13 UTC, hirokiterashima requested changes
When I delete a tag in my unit library, the tag still appears on the unit. I have to refresh the page to see the change. Can they be immediately removed without having to refresh?

The tag choices in the "Apply Tags" filter dialog doesn't seem to update immediately after you add or delete tags. It only seems to update when you edit the tag name or color.

2024-06-26 23:59 UTC, geoffreykwan commented
I've fixed the tags not updating bugs.

2024-06-27 17:26 UTC, hirokiterashima commented
I verified the new commit fixes the tags not updating bugs.

For all the new html files that were introduced in this PR, (manage-tags-dialog.component.html, color-chooser.component.html, etc) should we apply the same improvements that we've been making in our standalone component work? mainly:
- use new control flow syntax (```@if, @else if, @for,...```)
- use self-closing tags

This will make the template easier to read.

2024-06-28 01:27 UTC, geoffreykwan commented
Ok, I've fixed the tests, used the new flow control, and used self closing tags.

2024-06-28 15:35 UTC, hirokiterashima reviewed
New changes look good. I added some more code suggestions inline to improve control flow readability.

Also, I noticed that in the "Apply Tags" select dropdown, clicking on the choice span (not the checkbox, not the tag text, but the space next to those on the same row) does not add/delete the tag. The cursor is a pointer, so I expected it to add/delete. We should handle clicking on the entire row?

2024-06-28 15:35 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.html
> +    }
Switch test order and use ```@else``` for better readability?
```suggestion
    @if (showCreateTag) {
      <edit-tag (closeEvent)="showCreateTag = false" />
    } @else {
      <div>
        <button mat-flat-button color="primary" (click)="showCreateTag = !showCreateTag" i18n>
          + New Tag
        </button>
      </div>
    }
```

2024-06-28 15:35 UTC, hirokiterashima commented on src/app/teacher/manage-tags-dialog/manage-tags-dialog.component.html
> +              @if (!idToEditing[tag.id]) {
Use ```@else``` here?
```suggestion
              } @else {
```

2024-06-28 19:25 UTC, geoffreykwan commented
I've changed the flow control to use @if/@else and fixed the apply tags option bug.

2024-07-01 22:04 UTC, hirokiterashima approved these changes
LGTM

2024-07-01 22:05 UTC, breity approved these changes
Looks good. 👍

2024-07-01 22:06 UTC, merged

2024-07-01 22:11 UTC, geoffreykwan commented
:tada: This PR is included in version 5.154.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-Client/releases/tag/v5.154.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: