feat(Translation): Convert step title input to translatable
WISE-Community/WISE-Client pull request #1851
Opened 2024-07-02 01:59 UTC by geoffreykwan

## Changes
- Convert step title input to translatable input

## Test
- Make sure the step title is translatable

2024-07-02 17:41 UTC, hirokiterashima requested changes
1. Can we show the english text under the title like we do with other inputs?
<img width="515" alt="Screenshot 2024-07-02 at 10 35 41 AM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/4634aaa7-4f36-44c7-b085-1be6150d2eb8">

2. The ```Step Title {{ nodePosition }}:``` and ``` Lesson Title {{ nodePosition }}:``` i18n strings appear to be removed from messages.xlf. Shouldn't they be translatable?

2024-07-08 18:48 UTC, geoffreykwan commented
The English text now shows when authoring other languages. I moved the translations from the .html into the .ts file. I also fixed an issue with the width for all translatable inputs.

2024-07-08 21:28 UTC, hirokiterashima approved these changes
LGTM. I think you can remove the isGroupNode class variable.

2024-07-08 21:28 UTC, hirokiterashima commented on src/assets/wise5/authoringTool/node/edit-node-title/edit-node-title.component.ts
> +      this.projectService.getNodePositionById(this.node.id);
Remove isGroupNode class variable and use this.node.isGroup() directly in the ternary expression?
```suggestion
    this.label =
      (this.node.isGroup() ? $localize`Lesson Title` : $localize`Step Title`) +
      ' ' +
      this.projectService.getNodePositionById(this.node.id);
```

2024-07-08 22:30 UTC, merged