Data Explorer fixed axis
WISE-Community/WISE-Client pull request #19
Opened 2021-03-23 16:14 UTC by geoffreykwan

Enable Data Explorer in a Table component and choose which table columns to use for the x or y data. Make sure it works in the Authoring, Student, and Grading views.

Try these scenarios
- only X Data has a specified table column
- only Y Data has a specified table column
- X Data and Y Data have specified table columns
- using "Number of Series" greater than 1

Closes #14

2021-03-24 16:36 UTC, hirokiterashima commented on src/assets/wise5/components/table/tableController.ts
> +      dataExplorerSeriesIndex++
Nit: I think we should just use i instead of dataExplorerSeriesIndex. It makes the code shorter and easier to read. What do you think?

2021-03-24 16:37 UTC, hirokiterashima commented on src/assets/wise5/components/table/tableController.ts
> +    for (const singleDataExplorerSeries of this.dataExplorerSeries) {
Nit: I think we should just use series here instead of singleDataExplorerSeries. It makes the code shorter and easier to read. What do you think?

2021-03-24 16:38 UTC, hirokiterashima commented on src/assets/wise5/components/table/tableController.ts
> +    for (const singleDataExplorerSeries of this.dataExplorerSeries) {
Nit: I think we should just use series here instead of singleDataExplorerSeries. It makes the code shorter and easier to read. What do you think?

2021-03-24 16:38 UTC, hirokiterashima commented on src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.ts
> +    return firstRow.length;
```suggestion
    return componentContent.tableData[0].length;
```

2021-03-24 16:45 UTC, hirokiterashima requested changes
Functionality looks good. See my code comments inline. Some are nit picky (marked 'nit'), so I'll leave it to you to change or not.

2021-03-24 16:46 UTC, hirokiterashima commented on src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.ts
> +    return columnNames;
```suggestion
    const firstRow = componentContent.tableData[0];
    return firstRow.map((cell) => {
      return cell.text;
    })
```

2021-03-24 21:02 UTC, breity requested changes
Looking good for the most part. A couple issues:
1. The axis label for a fixed column is blank and can only be changed by typing in a value if "Can Student Edit Axis Labels" is true. If that is set to false, there will be no label for the axis. We should default to the column header.
2. The series and axis colors don't match when there are multiple axes and series set. Regression lines are also a different color if they're enabled for scatterplots. (Maybe this isn't related to the PR?)
![image](https://user-images.githubusercontent.com/297450/112382760-7ed23880-8ca9-11eb-9362-61027af43e04.png)

2021-03-24 21:04 UTC, breity commented on src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.html
> +        <p>Fix Data to Table Column <span><md-icon>help</md-icon><md-tooltip style="height: auto" md-direction="right">You can author x or y data to always use a specific table column.<br/>The studen
The text here (and in some other places) isn't translatable. Maybe we could wait until this is upgraded to Angular to add `$localize` tags?

2021-03-30 18:55 UTC, breity approved these changes
Looks good!

2021-03-31 15:13 UTC, hirokiterashima approved these changes

2021-03-31 15:43 UTC, hirokiterashima commented
Tested against production.

2021-03-31 15:44 UTC, merged