feat(Data Export): Implement Embedded table export
WISE-Community/WISE-Client pull request #383
Opened 2021-10-26 21:37 UTC by geoffreykwan

Make sure the "Export Component Data" works properly when exporting data saved in the Embedded table on this step.

In order for this device table to be exportable, the component must have the tag devices-kwh-co2-table
[3.3 A: Investigation #2: Device Usage Plan](https://wise.berkeley.edu/preview/unit/32968/node162)
You can use the updated model (that properly saves every time) that I've placed in the shared curriculum folder [appliances-new.html](https://wise.berkeley.edu/curriculum/shared/appliances-kwh-co2-table/v1/appliances-new.html). If you want to download it locally, you will need the html, js, and styles.css files.

In order for this transportation table to be exportable, the component must have the tag transportation-co2-table
[3.3 B: Investigation #3: Transportation Plan](https://wise.berkeley.edu/preview/unit/32968/node163)
You can use the updated model (that properly saves every time) that I've placed in the shared curriculum folder [transportation-new.html](https://wise.berkeley.edu/curriculum/shared/transportation-co2-table/v1/transportation-new.html). If you want to download it locally, you will need the html, js, and styles.css files.

1. Launch the Classroom Monitor for the run
2. Go to the Data Export view
3. Click "Export Component Data"
4. Find the Embedded component
5. Click the "All" button and make sure it exports all the work
6. Click the "Latest" button and make sure it exports the latest work

Make sure the "Export Component Data" works for other components that can be exported such as Match or Discussion.

2021-10-26 23:11 UTC, hirokiterashima requested changes
Can you put the embeddedComponentExport functions into another class instead of adding it to dataExportController? 

Also see the inline code change suggestion to clarify the ```isDataSpring20201EmbeddedComponentAndCanExport``` function.

2021-10-26 23:11 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/dataExport/dataExportController.ts
>      }
```suggestion
  isDataSpring20201EmbeddedComponentAndCanExport(component: any): boolean {
    return component.type === 'Embedded' && component.tags != null && 
        component.tags.includes('DataSpring20201');
```
This function should always return a boolean value. Right now it can return true or void.

2021-10-27 15:59 UTC, geoffreykwan commented on src/assets/wise5/classroomMonitor/dataExport/dataExportController.ts
>      }
Ok, fixed the function.

I think we should move all the component specific exports into their own classes in another issue. All the different export types should also be in their own routes and classes (work export, events export, notebook export, etc) and done in another issue as well.

2021-10-27 16:06 UTC, geoffreykwan commented
I've added another Embedded table model (transportation) to test for exporting in the description.

2021-10-27 19:03 UTC, hirokiterashima approved these changes

2021-10-27 19:04 UTC, merged