feat(Authoring): Implement Peer Group Activity Tag authoring
WISE-Community/WISE-Client pull request #480
Opened 2022-02-02 23:43 UTC by geoffreykwan

Make sure you can author the Peer Group Activity Tag in the advanced authoring view for components that save work.

Closes #479

2022-02-03 18:51 UTC, hirokiterashima requested changes
Each time I type a letter in the peerGroupActivityTag input box, it creates a new row in the peer_group_activities table because it's saving changes per keystroke. Can you change this to save when input loses focus, or after a debounce?

Also, see code comments inline.

2022-02-03 18:51 UTC, hirokiterashima commented on src/app/authoring-tool/edit-component-peer-group-activity-tag/edit-component-peer-group-activity-tag.component.ts
> +  }
Would it be cleaner if tagsFound is a Set<string> in this function? 
```suggestion
  getPeerGroupActivityTags(): string[] {
    const tagsFound = new Set();
    for (const component of this.projectService.getComponents()) {
      const tag = component.peerGroupActivityTag;
      if (tag != null && tag !== '') {
        tagsFound.add(tag);
      }
    }
    return Array.from(tagsFound).sort();
  }
```

2022-02-03 18:51 UTC, hirokiterashima commented on src/assets/wise5/components/peerChat/edit-peer-chat-advanced-component/edit-peer-chat-advanced-component.component.ts
> +  }
Not necessary?

```suggestion
```

2022-02-07 18:19 UTC, geoffreykwan commented
I wonder if losing focus or debounce won't be good enough. Both of those can still lead to unwanted rows in the database.

Should we have a confirm dialog when adding a new tag?
Should we check for duplicate tags before saving a tag?
Should authors be able to delete tags?

2022-02-08 17:42 UTC, hirokiterashima approved these changes
Looks good.

2022-02-08 17:44 UTC, merged