feat(Table): Use Tabulator to display Table component data
WISE-Community/WISE-Client pull request #696
Opened 2022-07-29 01:08 UTC by breity

## Changes
- Use Tabulator to display Table components in the VLE and grading.
- Adds column sorting and table scrolling.

Height is currently set to a max of 500px.
Column widths are automatically set by Tabulator if global cell size is not set or is set to 10 (the default). Column widths are approximated into pixels for Tabulator by multiplying the size set in the authoring tool by 16 (so a cell size of 20 = 320px wide). I'll create a new issue to modify the Table authoring to use pixels for column/cell widths.

Closes #332.

## Test
- Test that all table components work as before in the VLE using Tabulator.
- Test the students can change the value of editable cells and the changes are saved.
- Test that connected components that import work to Table components function as before.
- Test that Show My Work and Show Group Work display Table components correctly using Tabulator (and editable cells are disabled).
- Test that Table components display correctly in the Teacher Tools (and editable cells are disabled).

2022-07-29 23:47 UTC, geoffreykwan approved these changes
Everything seems to work properly. I noted some really minor code changes.

2022-07-29 23:47 UTC, geoffreykwan commented on src/assets/wise5/components/table/tabulatorDataService.ts
> +    let columns = [];
I think you can use const instead of let here.

2022-07-29 23:47 UTC, geoffreykwan commented on src/assets/wise5/components/table/tabulatorDataService.ts
> +    let rowData = {
I think you can use const instead of let here.

2022-08-01 17:59 UTC, hirokiterashima requested changes
Functionality works well. Please see inline comments.

2022-08-01 17:59 UTC, hirokiterashima commented on src/assets/wise5/components/table/tabulator-table/tabulator-table.component.ts
> +  options: any;
Is this neeed, or can we use tabOptions?

2022-08-01 17:59 UTC, hirokiterashima commented on src/assets/wise5/components/table/tabulator-table/tabulator-table.component.ts
> +    formatterParams: Tabulator.formatterParams
Do we need this param?

2022-08-01 17:59 UTC, hirokiterashima commented on src/assets/wise5/components/table/tabulator-table/tabulator-table.component.ts
> +  private cellEdited(cell: Tabulator.CellComponent) {
do we need this function, or just inline the emit() call?

2022-08-01 17:59 UTC, hirokiterashima commented on src/assets/wise5/components/table/tabulator-table/tabulator-table.component.ts
> +
remove line
```suggestion
```

2022-08-01 17:59 UTC, hirokiterashima commented on src/assets/wise5/components/table/tabulatorDataService.ts
> +  private getTabulatorColumn(columnDef: any, index: number, globalCellSize: number): any {
Can we define a TabulatorColumn class?

2022-08-01 20:37 UTC, breity commented
@geoffreykwan @hirokiterashima Thanks, I implemented requested changes.

2022-08-01 23:03 UTC, merged