feat(Table): Allow authors to specify frozen columns
WISE-Community/WISE-Client pull request #723
Opened 2022-08-09 00:16 UTC by breity

## Changes
Adds a checkbox for each column in Table component authoring that specifies whether the column in frozen or not.

Tabulator allows any number of frozen columns on each side of the table. Frozen columns must be next to each other. Once a non-frozen column is reached, Tabulator stops building the frozen list for that side of the table. Total number of frozen columns must be less than total number of columns.

Closes #715.

## Test
- When authoring a Table component Select the "Freeze" checkbox for any columns in the table.
- Verify in VLE (and grading) that any columns you checked are frozen in Tabulator (if they're next to each other).
- Verify that you can't select all of the columns to be frozen. (If you select n-1 frozen columns, the last remaining column should have it's 'Frozen' checkbox disabled.)

2022-08-09 17:38 UTC, hirokiterashima requested changes
Functionality works well. Please see comments inline.

2022-08-09 17:38 UTC, hirokiterashima commented on src/assets/wise5/components/table/table-authoring/table-authoring.component.ts
> +  }
Move variable declarations just before you need them
```suggestion
  private isfrozenColumnsLimitReached(): boolean {
    const firstRow = this.authoringComponentContent.tableData[0];
    if (firstRow == null) {
      return false;
    }
    let count = 0;
    for (const key in firstRow) {
      if (firstRow[key].frozen) {
        count++;
      }
    }
    const maxFrozen = firstRow.length - 1;
    return count === maxFrozen;
  }
```

2022-08-09 17:38 UTC, hirokiterashima commented on src/assets/wise5/components/table/table-authoring/table-authoring.component.html
> +              matTooltip="You can freeze any number of columns to the beginning or end of the table. Frozen columns must be next to each other."
Update tooltip text. Frozen columns do not need to be next to each other.

2022-08-10 20:32 UTC, breity commented
@hirokiterashima Thanks, I updated with the requested changes.

2022-08-10 22:13 UTC, hirokiterashima approved these changes
Looks good. Can you make this function private before you merge?
```
  setColumnCellSize(column: number, size: number): void {
```

2022-08-11 23:56 UTC, merged