refator(DialogGuidanceFeedbackRuleEvaluator): Extract TermEvaluators
WISE-Community/WISE-Client pull request #764
Opened 2022-08-23 17:02 UTC by hirokiterashima

## Changes
- Extract 3 term evaluators from DialogGuidanceFeedbackRuleEvaluator into their own class
   - HasKIScore => HasKIScoreTermEvaluator
   - IdeaCount[MoreThan|Equals|LessThan] => IdeaCountTermEvaluator
   - Idea => IdeaTermEvaluator
- Each evaluator extends abstract TermEvaluator class
- No new feature was added

## Test
- Dialog Guidance feedback works as before
   - single score, multiple score
   - rules: hasKIScore(X), ideaCount[MoreThan|Equals|LessThan](X), ideaX 

Closes #763

2022-08-23 19:02 UTC, geoffreykwan requested changes
Works well. I have some test change suggestions and a question.

2022-08-23 19:02 UTC, geoffreykwan commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaCountTermEvaluator.spec.ts
> +      const idea3 = new CRaterIdea('idea3', true);
Should the parameter to CRaterIdea not include the 'idea' text to more accurately represent how it's actually used when students have their work scored?
```
      const idea1 = new CRaterIdea('1', true);
      const idea2 = new CRaterIdea('2', true);
      const idea3 = new CRaterIdea('3', true);
```

2022-08-23 19:02 UTC, geoffreykwan commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaTermEvaluator.spec.ts
> +    response_with_2_ideas.ideas = [new CRaterIdea('idea1', true), new CRaterIdea('idea2', true)];
Should the parameter to CRaterIdea not include the 'idea' text?
```
    response_with_2_ideas.ideas = [new CRaterIdea('1', true), new CRaterIdea('2', true)];
```

2022-08-23 19:02 UTC, geoffreykwan commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaTermEvaluator.spec.ts
> +      const evaluator_idea1 = new IdeaTermEvaluator('idea1');
Should the parameter to IdeaTermEvaluator not include the 'idea' text?
```
      const evaluator_idea1 = new IdeaTermEvaluator('1');
```

2022-08-23 19:02 UTC, geoffreykwan commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaTermEvaluator.ts
> +    return this.term === 'true' || response.getDetectedIdeaNames().includes(this.term);
What is the purpose of ```this.term === 'true'```? Do authors actually use the true expression?

2022-08-24 16:50 UTC, hirokiterashima commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaTermEvaluator.ts
> +    return this.term === 'true' || response.getDetectedIdeaNames().includes(this.term);
The author would usually not use the true expression when writing rules (but they can if they want to).

The term 'true' or 'false' is created and added to the termStack by the application as it processes operator expressions like "&&", "||", and "!" (see ```DialogGuidanceFeedbackRuleEvaluator.evaluateOperator()```). 

If student had ideas 1, 2 and 3, evaluating the postfix expression ["1", "2", "&&", "3", "&&"] goes like this:
["1", "2", "&&", "3", "&&"] => ["true", "3", "&&"] => ["true"] => true.

I agree this code is confusing at a glance. For now, I can add a comment on the function about why we need this check, and we can think of a better way to write this in the future?

2022-08-24 19:18 UTC, geoffreykwan commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaTermEvaluator.ts
> +    return this.term === 'true' || response.getDetectedIdeaNames().includes(this.term);
Yea a comment would be fine.

2022-08-25 17:22 UTC, hirokiterashima commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaTermEvaluator.spec.ts
> +    response_with_2_ideas.ideas = [new CRaterIdea('idea1', true), new CRaterIdea('idea2', true)];
done

2022-08-25 17:22 UTC, hirokiterashima commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaTermEvaluator.ts
> +    return this.term === 'true' || response.getDetectedIdeaNames().includes(this.term);
Comment added.

2022-08-25 17:22 UTC, hirokiterashima commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaTermEvaluator.spec.ts
> +      const evaluator_idea1 = new IdeaTermEvaluator('idea1');
done

2022-08-25 17:23 UTC, hirokiterashima commented on src/assets/wise5/components/dialogGuidance/TermEvaluator/IdeaCountTermEvaluator.spec.ts
> +      const idea3 = new CRaterIdea('idea3', true);
done

2022-08-25 18:11 UTC, geoffreykwan approved these changes
Looks good.

2022-08-25 19:04 UTC, merged