fix(Login): Add redirectUrl to Google login url
WISE-Community/WISE-Client pull request #798
Opened 2022-09-07 16:51 UTC by hirokiterashima

## Changes
- When google login button is clicked in the homepage, it will append the redirect url to the google login url

## Test
- Test with PR

Closes #797

2022-09-07 19:07 UTC, geoffreykwan requested changes
Works well. I have a code clean up suggestion.

2022-09-07 19:08 UTC, geoffreykwan commented on src/app/login/login-home/login-home.component.ts
> +      : `${url}?accessCode=${this.accessCode}`;
Should this be rewritten to reduce duplication? Something like
```
return `${url}${url.includes('?') ? '%' : '?'}accessCode=${this.accessCode}`;
```
or
```
const delimiter = url.includes('?') ? '%' : '?';
return `${url}${delimiter}accessCode=${this.accessCode}`;
```

2022-09-09 16:03 UTC, breity approved these changes
Looks good.

2022-09-09 17:15 UTC, geoffreykwan approved these changes
Looks good.

2022-09-09 23:25 UTC, merged