feat(Dynamic Prompt): Evaluate rules using Peer Group work
WISE-Community/WISE-Client pull request #845
Opened 2022-10-06 18:57 UTC by geoffreykwan

## Changes

- FeedbackRuleEvaluator.getFeedbackRule() can now accept a single CRaterResponse or an array of CRaterResponses
- Dynamic prompt can figure out which dynamic prompt to display based on work and scores from the members of a Peer Chat group

## Test

- Make sure the FeedbackRuleEvaluator works when it receives one CRaterResponse (when you do not specify the dynamicPrompt.peerGroupingTag)
- Make sure the FeedbackRuleEvaluator works when it receives an array of CRaterResponses (when you specify the dynamicPrompt.peerGroupingTag)

Here is the Peer Chat component content I used for testing (when peerGroupingTag is specified).
```
{
    "id": "gkvyzuils1",
    "type": "PeerChat",
    "prompt": "",
    "showSaveButton": false,
    "showSubmitButton": false,
    "peerGroupingTag": "847zgyqp1p",
    "questionBank": [],
    "dynamicPrompt": {
        "enabled": true,
        "peerGroupingTag": "847zgyqp1p",
        "prePrompt": "This is the pre prompt",
        "postPrompt": "This is the post prompt",
        "referenceComponent": {
            "nodeId": "node49",
            "componentId": "2aabvbcukq"
        },
        "rules": [
            {
                "id": "4y3h9u0sdh",
                "expression": "isSecondToLastSubmit",
                "prompt": "Prompt when you still have a submit to use"
            },
            {
                "id": "df92gk754j",
                "expression": "2 && 3",
                "prompt": "Prompt when you got idea 2 and idea 3"
            },
            {
                "id": "7j2is1360s",
                "expression": "2 || 3",
                "prompt": "Prompt when you got idea 2 or idea 3"
            },
            {
                "id": "votbik4ncz",
                "expression": "hasKIScore(5)",
                "prompt": "Prompt when you got 5"
            },
            {
                "id": "hwp6sxf8vr",
                "expression": "hasKIScore(4)",
                "prompt": "Prompt when you got 4"
            },
            {
                "id": "swxzc0j7q0",
                "expression": "hasKIScore(3)",
                "prompt": "Prompt when you got 3"
            },
            {
                "id": "ebtgds3b1r",
                "expression": "hasKIScore(2)",
                "prompt": "Prompt when you got 2"
            },
            {
                "id": "z4yu37jcis",
                "expression": "hasKIScore(1)",
                "prompt": "Prompt when you got 1"
            },
            {
                "id": "isDefault",
                "expression": "isDefault",
                "prompt": "Default prompt"
            }
        ]
    }
}
```

#840

2022-10-06 20:36 UTC, hirokiterashima requested changes
Functionality works well. I wrote some inline code comment suggestions.

2022-10-06 20:36 UTC, hirokiterashima commented on src/assets/wise5/components/common/feedbackRule/FeedbackRuleEvaluator.ts
> +    }
Use ternary operator to reduce duplication and complexity
```suggestion
    return (
      this.hasMaxSubmitAndIsFinalSubmitRule(feedbackRule) &&
      (response instanceof CRaterResponse
        ? this.component.hasMaxSubmitCountAndUsedAllSubmits(response.submitCounter)
        : response.some((response: CRaterResponse) => {
            return this.component.hasMaxSubmitCountAndUsedAllSubmits(response.submitCounter);
          }))
    );
```

2022-10-06 20:36 UTC, hirokiterashima commented on src/assets/wise5/components/common/feedbackRule/FeedbackRuleEvaluator.ts
> +    }
Use ternary operator to reduce duplication and complexity
```suggestion
    return (
      this.hasMaxSubmitAndIsSecondToLastSubmitRule(feedbackRule) &&
      (response instanceof CRaterResponse
        ? this.isSecondToLastSubmit(response.submitCounter)
        : response.some((response: CRaterResponse) => {
            return this.isSecondToLastSubmit(response.submitCounter);
          }))
    );
```

2022-10-06 20:36 UTC, hirokiterashima commented on src/assets/wise5/components/common/feedbackRule/FeedbackRuleEvaluator.ts
> +    }
Use ternary operator to reduce duplication and complexity

2022-10-06 20:36 UTC, hirokiterashima commented on src/assets/wise5/components/common/feedbackRule/FeedbackRuleEvaluator.ts
> +    }
Use ternary operator to reduce duplication and complexity

2022-10-07 15:31 UTC, geoffreykwan commented
Changing those sections to ternary make them a lot harder to read.

2022-10-07 16:48 UTC, hirokiterashima commented
The issue I have with the code is the duplication and complexity that they add. The code becomes longer and more repetitive. I think ternary conditional solves those issues, and to me they don't make the code a lot harder to read; I'm reading less code and the logic is easy to follow. We can also ask @breity what he thinks.

Can you suggest another way to write the code that avoids those issues?

2022-10-11 16:35 UTC, hirokiterashima approved these changes
LGTM

2022-10-11 19:29 UTC, merged