chore(Classroom Monitor): Convert student progress view
WISE-Community/WISE-Client pull request #948
Opened 2022-12-12 16:00 UTC by geoffreykwan

## Changes

Converted student progress to Angular.

## Test

1. Open a run in the Classroom Monitor
2. Go to the "Grade By Team" view
3. Make sure everything works like before
- Find a student
- Sort by column
- Mouseover tooltips
- Clicking on a workgroup
- Make sure things update in real time like student location
- Changing period shows correct workgroups

@breity The sticky header row doesn't stick anymore. Can you see if you can fix this? If not, it's ok if we don't have the sticky functionality anymore since our other views don't have it and we can always add it back when we redesign.

Closes #947

2022-12-16 17:49 UTC, breity approved these changes
Looks good.

I made some minor style updates. I removed the old sticky header code for now.

2022-12-20 18:35 UTC, breity requested changes

2022-12-20 18:35 UTC, breity commented on src/assets/wise5/classroomMonitor/student-progress/student-progress.component.ts
> +      }
The if-else cases in the sort functions can be refactored a bit to reduce complexity. For example:
```suggestion
      if (completionA === completionB) {
        return workgroupA.username.localeCompare(workgroupB.username);
      }
      return direction === 'asc' ? completionA - completionB : completionB - completionA;
```

2022-12-21 05:12 UTC, breity requested changes

2022-12-21 05:12 UTC, breity commented on src/assets/wise5/classroomMonitor/student-progress/student-progress.component.ts
> +      }
This could also be converted to a ternary operator so there's only need for 1 return.

2022-12-21 05:12 UTC, breity commented on src/assets/wise5/classroomMonitor/student-progress/student-progress.component.ts
> +      }
Same here. Could reduce complexity by using a ternary operator.

2022-12-21 15:24 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/student-progress/student-progress.component.spec.ts
> +const workgroupId5 = testHelper.workgroupId5;
```suggestion
const {workgroupId1, workgroupId2, workgroupId3, workgroupId4, workgroupId5} = testHelper;
```

2022-12-21 15:26 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/student-progress/student-progress.component.spec.ts
> +}
Make this into a SortTestParams class instead?

2022-12-21 15:28 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/student-progress/student-progress.component.ts
> +    }
Is this the same (but with fewer lines)?
```suggestion
    this.sortedTeams = [...this.teams];
```

2022-12-21 15:34 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/student-progress/student-progress.component.spec.ts
> +}
Convert into a WorkgroupForTesting class?

2022-12-22 03:28 UTC, hirokiterashima approved these changes
LGTM.

2022-12-22 06:37 UTC, breity approved these changes
Looks good.

2022-12-22 15:45 UTC, merged