chore(Milestone Details): Upgrade from AngularJS to Angular
WISE-Community/WISE-Client pull request #956
Opened 2022-12-19 18:41 UTC by hirokiterashima

## Notes
- @breity please edit styling as you see fit, in particular:
   - Milestone report graphs appear vertically instead of horizontally inline
   -  "Student completion" view, in particular
<img width="1241" alt="Screenshot 2022-12-19 at 9 45 42 AM" src="https://user-images.githubusercontent.com/119416/208495772-01c3b625-2361-4650-8792-5b1986317b1f.png">

## Changes
- Register MilestoneReportGraph/Data as WebComponents to get them to render dynamically in authored content
- Moved all milestone* component declarations to ClassroomMonitorModule for now
   - Will make a separate PR to break up ClassroomMonitorModule into separate modules. Doing this in the PR would have created too many file changes and expanded scope
- Clean up code

## Test Prep
- Run ```npm install``` to get dependency

## Test
- Milestone report works as before
   - report graph and data are computed and rendered properly 
- If report is...
   - available: can view/grade student work
   - not available: can view student progress
- Step info displays in another popup dialog

Closes #955

2023-01-12 23:49 UTC, breity requested changes
I updated and fixed the styling issues.

This looks good for the most part, but viewing student work when there are multiple locations for a milestone is broken now.

![Screen Shot 2023-01-12 at 3 48 03 PM](https://user-images.githubusercontent.com/297450/212205027-3a1fe19f-d896-47ad-8f43-cb0ae0298f6b.png)

I see some js errors related to the milestone graphs, but the graphs do seem to render properly. I also see a server error:
```
wise-api     | java.lang.NullPointerException
wise-api     | 	at rufus.lzstring4java.LZString.getBaseValue(LZString.java:36)
wise-api     | 	at rufus.lzstring4java.LZString.access$300(LZString.java:16)
wise-api     | 	at rufus.lzstring4java.LZString$6.doFunc(LZString.java:123)
wise-api     | 	at rufus.lzstring4java.LZString._decompress(LZString.java:404)
wise-api     | 	at rufus.lzstring4java.LZString.decompressFromEncodedURIComponent(LZString.java:120)
wise-api     | 	at org.wise.vle.web.wise5.TeacherGetDataController.getComponentsList(TeacherGetDataController.java:82)
wise-api     | 	at org.wise.vle.web.wise5.TeacherGetDataController.getData(TeacherGetDataController.java:61)
...
```

2023-01-13 20:00 UTC, hirokiterashima commented
@breity looks like we just needed to merge the latest from develop into this branch (because your API was using a new way to parse components param). PTAL.

2023-01-13 21:55 UTC, geoffreykwan requested changes
Switching between periods in the Milestone dialog won't update the graph data.

2023-01-13 21:55 UTC, geoffreykwan commented on src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestone-details/milestone-details.component.html
> +
This file has an empty new line at the top which can be deleted.

2023-01-17 17:54 UTC, breity commented
@hirokiterashima Multiple locations works now that the latest from develop has been merged. ✅ 

I see the same issue with switching periods that @geoffreykwan identified (MilestoneReportGraph and MilestoneReportData instances don't update).

2023-01-18 19:50 UTC, hirokiterashima commented
Fixed the issue updating graph/data when period changes. PTAL.

2023-01-19 16:29 UTC, geoffreykwan approved these changes
Looks good.

2023-01-19 19:17 UTC, breity approved these changes
LGTM.

2023-01-19 21:37 UTC, merged