Created Node class
WISE-Community/WISE-Client pull request #98
Opened 2021-04-23 21:53 UTC by hirokiterashima

## Changes

- Created Node class
- Moved ProjectService.getNodeIconByNodeId() to Node.getIcon()
- Updated references and cleaned up function for readability
- Added unit tests

## Test

- Update node icons in the AT by adding/editing the icons JSON block for a step or group.
Here's a sample icons JSON block:
```
"icons": {
        "default": {
            "fontName": "info",
            "color": "#2196F3",
            "fontSet": "material-icons",
            "type": "font"
        }
    }
```

Verify that node icons appear correctly in CM, AT, VLE.

#97

2021-04-26 16:27 UTC, geoffreykwan requested changes
Functionality works well. I posted a couple questions below.

2021-04-26 16:27 UTC, geoffreykwan commented on src/assets/wise5/services/projectService.ts
> +    return Object.assign(new Node(), this.getNodeById(nodeId));
Should we cache the Node object each time it's generated for a given nodeId?

2021-04-26 16:27 UTC, geoffreykwan commented on src/assets/wise5/common/Node.ts
> +  }
Does the node icon ever change? If not, maybe we should save the icon object to an instance variable. If it does, we can leave it as is. getIcon() gets called for every node in the project whenever you go to another step.

2021-04-26 20:50 UTC, hirokiterashima commented
I cached the Node and NodeIcon values in private fields.

2021-04-27 18:59 UTC, geoffreykwan approved these changes
Looks good.

2021-04-27 18:59 UTC, merged