chore(Classroom Monitor): Convert show node info dialog
WISE-Community/WISE-Client pull request #991
Opened 2023-01-30 15:32 UTC by geoffreykwan

## Changes

Converted Show Node Info dialog to Angular.

## Test

Make sure the "Step Info" dialog works properly in
- Grade By Step > Click a step > Click "Step Info" in the upper right
- Milestones view > Click a milestone > Click "(Step Info)" link
- Make sure "Open in New Window" button works

Closes #988

2023-01-30 17:18 UTC, hirokiterashima requested changes
Feature works well. 

The header in the step info dialog is slightly different from what's in production.

Production:
<img width="851" alt="Screenshot 2023-01-30 at 9 12 41 AM" src="https://user-images.githubusercontent.com/119416/215547755-7b80df54-89ff-4f31-910c-ebe1aa666195.png">

This PR:
<img width="735" alt="Screenshot 2023-01-30 at 9 13 54 AM" src="https://user-images.githubusercontent.com/119416/215547783-84592f94-1354-402b-8a0a-113b833086ad.png">

Can you get it to match? Also, see inline comment.

2023-01-30 17:18 UTC, hirokiterashima commented on src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/node-grading-view/node-grading-view.component.ts
> +  showRubric() {
```suggestion
  protected showRubric(): void {
```

2023-01-31 23:54 UTC, breity approved these changes
LGTM.

I updated the dialog styles to match the other Angular Material dialogs in CM (student revisions, etc.).

2023-02-01 16:44 UTC, hirokiterashima approved these changes
LGTM

2023-02-01 17:31 UTC, merged